Web profile page
bounswe/bounswe2024group11 pull request #358
Opened 2024-05-12 13:40 UTC by hks1444

- Created initial profile page UI
- It has no functionality yet

2024-05-12 13:45 UTC, umitcan07 requested changes
Plase do not serve svg files in public dir. Use Remixicon inlined. Refer to my implementation on Feed page please.
```
import { RiHeartFill } from "@remixicon/react";

const MyComponent = () => {
    return (
        <RiHeartFill
            size={36} // set custom `width` and `height`
            color="red" // set `fill` color
            className="my-icon" // add custom class name
        />
    );
};
```

2024-05-12 13:45 UTC, umitcan07 commented
can we rename the pr title accordingly?

2024-05-12 14:13 UTC, hks1444 commented
I didn't understand how should I do it and use these icons?

2024-05-14 11:40 UTC, umitcan07 approved these changes

2024-05-14 11:40 UTC, merged