wip dev to main
bounswe/bounswe2024group11 pull request #511
Opened 2024-10-11 18:47 UTC by umitcan07

merge for the first prod deployment

2024-10-25 13:55 UTC, umitcan07 commented
CI/CD fail is expected, let's not be blocked by it!

2024-10-25 15:51 UTC, ozankrkya commented on .github/workflows/aws_dev.yml
- This workflow is currently generated for development environment in AWS.
- It will be re-configured with environment variables and secrets, this version is not completed.
- Also another workflow will be configured for prod environment.

2024-10-25 15:52 UTC, ozankrkya commented on Makefile
This makefile is currently in use (Milestone 1) since workflows are not ready to execute.

2024-10-25 15:53 UTC, ozankrkya commented on backend/README.md
This readme can be updated later on.

2024-10-25 15:53 UTC, ozankrkya commented on backend/config/settings.py
More configuration will be added later during the connection process with frontend.

2024-10-25 15:55 UTC, ozankrkya commented on backend/wait-for-it.sh
This scripts is needed for health check in docker-compose builds.

2024-10-25 15:55 UTC, ozankrkya commented on client/.env.example
Will be reviewed later, right now it uses mock server.

2024-10-25 15:57 UTC, ozankrkya commented on docker-compose.dev.yml
It can be used for local deployment, however, docker-compose.dev.yml is preferred.

2024-10-25 15:57 UTC, ozankrkya commented on docker-compose.yml
It can be used for local deployment, however, docker-compose.dev.yml is preferred.

2024-10-25 18:56 UTC, Meminseeker requested changes
The `package.json` and the `pnpm-lock.yaml` files at the root level should be removed

2024-10-25 18:56 UTC, Meminseeker commented on client/public/innovator.woff2
What is this?

2024-10-25 18:56 UTC, Meminseeker commented on package.json
Why is there a package.json file at the root level

2024-10-25 18:56 UTC, Meminseeker commented on pnpm-lock.yaml
Why is there a pnpm-lock.yaml file at the root level

2024-11-19 18:40 UTC, Meminseeker approved these changes
My comments are satisfied

2024-11-20 21:30 UTC, umitcan07 commented
we need reviews here. reviews that are virtually impossible to justify :D

2024-11-20 21:34 UTC, merged