Implement quiz id route
bounswe/bounswe2024group11 pull request #548
Opened 2024-10-18 20:02 UTC by hks1444

2024-10-18 20:03 UTC, umitcan07 commented
pr title please

2024-10-18 20:04 UTC, umitcan07 commented on client/src/routes/Quiz.tsx
> +            selectedOption === ""
why is this?

2024-10-18 20:05 UTC, umitcan07 commented on client/src/routes/Quiz.tsx
> +            selectedOption === ""
why do we have these as functions instead of variables?
just assign it to what's returned.

`const isPrevDisabled = currentQuestion === 0`

2024-10-18 20:06 UTC, umitcan07 commented on client/src/routes/Quiz.tsx
> +                onClick={() => setCurrentQuestion(currentQuestion + 1)}
its a pattern to use it like 
`setCurrentQuestion(currentQuestion => currentQuestion + 1)`

2024-10-18 20:06 UTC, umitcan07 requested changes
please resolve my comments <3

2024-10-19 11:29 UTC, hks1444 commented
I implemented the changes you requested.

2024-10-19 11:40 UTC, umitcan07 approved these changes

2024-10-19 11:41 UTC, umitcan07 commented
good job mate

2024-10-19 11:41 UTC, merged